name: Build and Release Packages

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and FPM
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential rpm zstd libarchive-tools
          sudo gem install --no-document fpm

      - name: Build Packages
        run: |
          RAW_VERSION=${GITHUB_REF_NAME#v}
          VERSION=$([ "$RAW_VERSION" == "main" ] || [ -z "$RAW_VERSION" ] && echo "0.0.1" || echo "$RAW_VERSION")
          
          echo "Building version: $VERSION"
          
          FORMATS=("deb" "rpm" "pacman")
          
          for FMT in "${FORMATS[@]}"; do
            fpm -s dir -t $FMT \
              -n amnezia-backup \
              -v $VERSION \
              --description "Backup script for AmneziaVPN" \
              --url "https://github.com/nastyagrifon/amnezia-backup" \
              --license "MIT" \
              -d "bash" -d "curl" \
              amnezia-backup.sh=/usr/bin/amnezia-backup
          done

      - name: Upload Artifacts to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        with:
          files: |
            *.deb
            *.rpm
            *.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
